apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: busybox-new
  namespace: git-config
spec:
  releaseName: busyboxchart
  chart:
    spec:
      chart: busyboxchart
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: git-config
      version: "0.1.0"
  interval: 0h1m0s