apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: busybox
  namespace: busybox
spec:
  releaseName: busyboxchart
  chart:
    spec:
      chart: busyboxchart
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: busybox
      version: "0.1.0"
  interval: 0h1m0s